// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IoTControlPanel.Models;

public partial class AlertBell
{
    public string GUID { get; set; }

    public string SensorIP { get; set; }

    public string LogTime { get; set; }
}