// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IoTControlPanel.Models;

public partial class Gift
{
    public string GiftName { get; set; }

    public string Member { get; set; }

    public int status { get; set; }

    public string RemoteAddr { get; set; }

    public string MemberDesc { get; set; }
}