// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IoTControlPanel.Models;

public partial class IoTDBdbContext : DbContext
{
    public IoTDBdbContext()
    {
    }

    public IoTDBdbContext(DbContextOptions<IoTDBdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TempLog> TempLog { get; set; }

    public virtual DbSet<TempLog2> TempLog2 { get; set; }

    public virtual DbSet<test> test { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlite("Data Source=D:\\IoTMVC\\IoTDB.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TempLog>(entity =>
        {
            entity.HasKey(e => e.GUID);

            entity.Property(e => e.GUID).HasColumnType("TEXT (36)");
            entity.Property(e => e.HUMI).HasColumnType("TEXT (10)");
            entity.Property(e => e.TEMP).HasColumnType("TEXT (10)");
            entity.Property(e => e.Time).HasColumnType("TEXT (30)");
        });

        modelBuilder.Entity<TempLog2>(entity =>
        {
            entity.HasKey(e => e.GUID);

            entity.Property(e => e.GUID).HasColumnType("TEXT (36)");
            entity.Property(e => e.HUMI).HasColumnType("TEXT (10)");
            entity.Property(e => e.TEMP).HasColumnType("TEXT (10)");
            entity.Property(e => e.Time).HasColumnType("TEXT (30)");
        });

        modelBuilder.Entity<test>(entity =>
        {
            entity.HasKey(e => e.GUID);

            entity.Property(e => e.GUID).HasColumnType("TEXT (36)");
            entity.Property(e => e.HUMI).HasColumnType("TEXT (10)");
            entity.Property(e => e.TEMP).HasColumnType("TEXT (10)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}