// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IoTControlPanel.Models;

public partial class LogLightChange
{
    public string GUID { get; set; }

    public int? LightNum { get; set; }

    public string SensorIP { get; set; }

    public string UpdateTime { get; set; }
}