// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IoTControlPanel.Models;

public partial class Member
{
    public string Name { get; set; }

    public string Desc { get; set; }

    public int Ans1 { get; set; }

    public int Ans2 { get; set; }

    public int Ans3 { get; set; }
}