// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IoTControlPanel.Models;

public partial class TempLog2
{
    public string GUID { get; set; }

    public string Time { get; set; }

    public string TEMP { get; set; }

    public string HUMI { get; set; }
}